### ISSUE TITLE
API - documentation

### ISSUE THREAD

**Issue by gforge** [AlexMili/torch-dataframe#10]
You have currently used a system similar to [LDoc](https://stevedonovan.github.io/ldoc/manual/doc.md.html) but it doesn't entirely follow those rules. It may be worth changing the syntax to something that provides an automated documentation for at least the API. Coming from R I'm used to using [roxygen2](https://cran.r-project.org/web/packages/roxygen2/vignettes/roxygen2.html) that handles this entire problem in an excellent fashion. 

I also like the `dok.unpack` functionality and it basically takes care of all the documentation (except the return value). Ideally I would like to combine the `dok.unpack` with [LDoc](https://stevedonovan.github.io/ldoc/manual/doc.md.html) but I guess that would require adding an LDoc extension. I'm pretty sure that there is some way of getting the [torch/dok](https://github.com/torch/dok) to generate documentation but for a documentation package it is surprisingly poorly documented.

**Comment by AlexMili** [comment]
I am investigating the `dok.unpack` option :)

**Comment by AlexMili** [comment]
Since #17 I think `dok` is no longer a suitable solution. LDoc seems a good march for our needs.

**Comment by gforge** [comment]
I agree. I still feel though that named parameters are a good thing and I suggest we keep dok.unpack when the parameters are > 2

**Comment by gforge** [comment]
The API docs are now available in the development branch through [argcheck](https://github.com/torch/argcheck). The remaining issue before closure is adding TOC and/or splitting into multiple files
