### ISSUE TITLE
__init fails with table input

### ISSUE THREAD

**Issue by gforge** [AlexMili/torch-dataframe#17]
Noticed that the Dataframe can't be initialized with a simple table:

``` lua
function df_tests.__init()
   local a = Dataframe("simple_short.csv")
   tester:eq(a:shape(), {rows=4, cols=3},
     "The simple_short.csv is 4x3")

   local b = Dataframe({['first_column']=3,['second_column']={10,11,12}})
   tester:assertTableEq(b:get_column("first_column"), {3,3,3})
   tester:assertTableEq(b:get_column("second_column"), {10,11,12})
end
```

I added the ability to have an argument in the __init for quickly loading a CSV but hadn't checked if it works with tables and unfortunately it seems that dok.unpack has issues with tables as arguments.

**Comment by AlexMili** [comment]
I am currently implementing Behaviour Driven Development specs and it is exactly the piece of code I was testing !
I am working on it ^^

**Comment by AlexMili** [comment]
I just posted an issue on torch/dok#13.
It seems that they have trouble with table as non-required arguments. As a workaround you can call the init as follows :

``` lua
local df = Dataframe{csv_or_data={['my_table']={}}}
```

I am going to remove `dok.unpack` from `__init()` for now and I will put it back when it will be fixed.

**Comment by AlexMili** [comment]
Ok the problem is also present for required table arguments.

``` lua
df:load_table({['my_table']={}})
```

doesn't work but

``` lua
df:load_table{data={['my_table']={}}}
```

does

**Comment by gforge** [comment]
I suspected that. In the `__init` there is no real need for multiple arguments, a pity about load_table. A side issue is if we should use `verbose = false` when called from the constructor. 

Btw - looked at your refactoring of the tests - nice approach. The `busted` package is neater than the torch test suite although I guess you need to figure out how to compare tensors.

**Comment by AlexMili** [comment]
I set it to `false`. It's a shortcut so no need to allow the direct access to the `verbose` argument. `load_csv` is here for that.

About `busted`, it's not exactly neater, it's different. Torch test suite is a unit-testing framework while `busted` is a behaviour driven test suite. One is more modern than the other ^^

`busted` allows to create custom matcher, I think I will use torch test suite for tensor comparison inside a custom matcher.

**Comment by gforge** [comment]
Looking at http://lua-users.org/wiki/NamedParameters I doubt that there is a good solution to this in Lua. I think `dok.unpack` is an excellent tool in all other instances but for `load_table` it may be inappropriate.

**Comment by gforge** [comment]
I think that argcheck with the usage of `env.istype` provides a possible solution:

``` lua
local argcheck = require 'argcheck'

test = torch.class('test')
test.__init =  argcheck{
  {name="self", type = "test"},
  call = function(self)
    self.data = "my_data"
  end
}

env = require 'argcheck.env' -- retrieve argcheck environement
env.istype = function(obj, typename)
  if (typename == "table|string") then
    return torch.type(obj) == "table" or
      torch.type(obj) == "string"
  end
  if (typename == "torch.*Tensor") then
    -- regular expressions don't work therefore this
    return torch.type(obj) == "torch.IntTensor" or
      torch.type(obj) == "torch.FloatTensor" or
      torch.type(obj) == "torch.DoubleTensor"
  end
  return torch.type(obj) == typename
end

test.__init = argcheck{
  {name="self", type = "test"},
  {name="tbl", type = "table|string"},
  overload = test.__init,
  call = function(self, tbl) -- called in case of success
    test.__init(self)
    print(self.data)
    print(tbl)
   end
}

a = test.new()
a = test.new("test")
a = test.new({1,2,3})
```

produces:

``` bash
$ th test.lua 
my_data 
test    
my_data 
{
  1 : 1
  2 : 2
  3 : 3
}
```

Unfortunately overloading does not work:

``` lua
local argcheck = require 'argcheck'

test = torch.class('test')
test.__init =  argcheck{
  {name="self", type = "test"},
  call = function(self)
    self.data = "my_data"
  end
}

test.__init = argcheck{
  {name="self", type = "test"},
  {name="data", type = "string"},
  overload = test.__init,
  call = function(self, data) -- called in case of success
    test.__init(self)
    print(self.data)
    print(data)
   end
}

test.__init = argcheck{
  {name="self", type = "test"},
  {name="data", type = "table"},
  overload = test.__init,
  call = function(self, data) -- called in case of success
    test.__init(self)
    print(self.data)
    print(data)
   end
}

a = test.new()
a = test.new("test")
a = test.new({1,2,3})
```

gives: 

``` bash
$ th test.lua 
/home/max/tools/torch/install/bin/luajit: ...max/tools/torch/install/share/lua/5.1/argcheck/graph.lua:147: argcheck rules led to ambiguous situations
stack traceback:
    [C]: in function 'error'
    ...max/tools/torch/install/share/lua/5.1/argcheck/graph.lua:147: in function 'addpath'
    .../max/tools/torch/install/share/lua/5.1/argcheck/init.lua:54: in function 'generaterules'
    .../max/tools/torch/install/share/lua/5.1/argcheck/init.lua:105: in function 'argcheck'
    test.lua:22: in main chunk
    [C]: in function 'dofile'
    ...ools/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00405d70
```

Shall we go with the first solution?

**Comment by gforge** [comment]
Sorry, noticed that there is still an issue if named parameters are provided:

``` lua
a = test.new{tbl = {"aaa"}}
```

prints

``` bash
my_data 
{
  tbl : 
    {
      1 : "aaa"
    }
}
```

**Comment by AlexMili** [comment]
`istype` seems to be the best solution since it doesn't require a named parameter

**Comment by gforge** [comment]
Fixed together with the argcheck Df_Dict update + minor bug (forgot to remove `verbose` argument when calling load_table)
