### ISSUE TITLE
Adding metatable functions

### ISSUE THREAD

**Issue by gforge** [AlexMili/torch-dataframe#18]
I think it would be nice to add some torch class [metatable functionality](https://github.com/torch/torch7/blob/master/doc/utility.md#torch.getmetatable) in addition to the `__tostring__`. The available methods according to the docs are:

``` lua
> for k, v in pairs(torch.getmetatable('torch.CharStorage')) do print(k, v) end

__index__       function: 0x1a4ba80
__typename      torch.CharStorage
write           function: 0x1a49cc0
__tostring__    function: 0x1a586e0
__newindex__    function: 0x1a4ba40
string          function: 0x1a4d860
__version       1
read            function: 0x1a4d840
copy            function: 0x1a49c80
__len__         function: 0x1a37440
fill            function: 0x1a375c0
resize          function: 0x1a37580
__index         table: 0x1a4a080
size            function: 0x1a4ba20
```
### Single number

Calling `__index__` with a number should naturally return a single row. The return object should be a dataframe and either we change the current `get_row` to use the [`_create_subset`](https://github.com/AlexMili/torch-dataframe/blob/master/Extensions/select_set_update.lua#L96-L120) or we call that directly.
### A table or tensor with integers

This should probably work just as the `_create_subset`
### A string value

I'm not sure if it is a good idea but a string value could result in `get_column` since columns are always strings.
### Single number

A simple call to [`_update_single_row`](https://github.com/AlexMili/torch-dataframe/blob/master/Extensions/select_set_update.lua#L212-L221) after asserting that the index exists.

If index is `self.n_rows + 1` then [`insert`](https://github.com/AlexMili/torch-dataframe/blob/master/main.lua#L263-L331) should be invoked.
### String

If column exists it should `drop` the column if argument is `nil` otherwise throw an error. 

If string is non-existant it should call the [`add_column`](https://github.com/AlexMili/torch-dataframe/blob/master/main.lua#L180-L204)
## `__len__`

Returns the `self.n_rows`
## `size`

Should return `shape()["rows"]` when called with `size(1)` and `shape()["cols"]` when called with `size(2)`. Empty string returns unnamed table with `{no_rows, no_cols}`, possibly it should return a tensor for sticking with the Torch [spirit](https://github.com/torch/torch7/blob/master/doc/tensor.md)
## `copy`

A call to `clone` and `_copy_meta` should do it.

**Comment by AlexMili** [comment]
Cool idea !

Though I am not sure about returning a Dataframe for a single row and with a string as argument. Generally when I use `__index` equivalent in other languages is to directly have the raw data.

About `size` returning a tensor seems the best option, there is still the `shape` function anyway.

**Comment by AlexMili** [comment]
`__eq` meta function could be useful for tests purpose.
