### ISSUE TITLE
Make where() returns all matching entries

### ISSUE THREAD

**Issue by AlexMili** [AlexMili/torch-dataframe#2]
> One thing that I think should be fixed is the `where`, it currently fetches the first match - the [Pandas where](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.where.html) returns all matching entries. One way would be to have a _private_ `_where` that returns the index numbers that the `update()` also uses.
> <cite>@gforge</cite>

**Comment by gforge** [comment]
I think the return value should be a new Dataframe-object populated with the rows that it has found during the where search, do you agree?

**Comment by AlexMili** [comment]
Yes, I agree !
