### ISSUE TITLE
Problem with rockspec 1.0.0

### ISSUE THREAD

**Issue by gforge** [AlexMili/torch-dataframe#20]
I'm trying to build my nvidia-docker with the package but I run into this error:

``` bash
RUN luarocks install https://raw.githubusercontent.com/AlexMili/torch-dataframe/master/torch-dataframe-1.0-0.rockspec
 ---> Running in 187ece69d55c

Error: Directory v1.0-0 not found inside archive v1.0-0.tar.gz
Using https://raw.githubusercontent.com/AlexMili/torch-dataframe/master/torch-dataframe-1.0-0.rockspec... switching to 'build' mode
The command '/bin/sh -c luarocks install https://raw.githubusercontent.com/AlexMili/torch-dataframe/master/torch-dataframe-1.0-0.rockspec' returned a non-zero code: 1

```

**Comment by AlexMili** [comment]
Forgot to link the commit x) (See ebd8a992a4de2ffc2a6b3a89c82136ef02fdcdda)
I added the directory name to the rockspec, now it should be working

**Comment by gforge** [comment]
Works:

``` bash
RUN luarocks install https://raw.githubusercontent.com/AlexMili/torch-dataframe/master/torch-dataframe-1.0-0.rockspec
 ---> Running in 6ad906c6b59c
Using https://raw.githubusercontent.com/AlexMili/torch-dataframe/master/torch-dataframe-1.0-0.rockspec... switching to 'build' mode
Updating manifest for /root/torch/install/lib/luarocks/rocks
torch-dataframe 1.0-0 is now built and installed in /root/torch/install/ (license: MIT/X11)
```

Still issues though with installing via `luarocks install torch-dataframe`:

``` bash
RUN luarocks install torch-dataframe
 ---> Running in 2dd7133c1c5a
Cloning into 'torch-dataframe'...
cp: cannot stat 'Dataframe.lua': No such file or directory

Error: Build error: Failed installing Dataframe.lua in /root/torch/install/lib/luarocks/rocks/torch-dataframe/0.1-1/lua/Dataframe.lua
Installing https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/torch-dataframe-0.1-1.rockspec...
Using https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/torch-dataframe-0.1-1.rockspec... switching to 'build' mode
The command '/bin/sh -c luarocks install torch-dataframe' returned a non-zero code: 1
```

As you can see it tries to fall back onto 0.1.1 but since the file has been deleted it fails. I know many packages have a rockspec directory, see [lfs](https://github.com/keplerproject/luafilesystem/tree/master/rockspecs) where both new and old are present. It may also be useful to have a dev-rockspec that is the dev version, see the popular [LuaSocket](https://luarocks.org/modules/luarocks/luasocket).

**Comment by AlexMili** [comment]
`Luarocks` uses some repositories which mirror some other repositories. In our case, the repository is from @rocks-moonscript-org but it hasn't be updated for the last 3 days. That's why the error...

A specific directory is totally what we need.

**Comment by gforge** [comment]
Great, I'll close this bug since the directory is more of a feature
