### ISSUE TITLE
load_table ex from README

### ISSUE THREAD

**Issue by tommy-u** [AlexMili/torch-dataframe#25]
I'm failing to run the following script from the README:

```
require 'Dataframe'
df = Dataframe()    
df:load_table{data={['firstColumn']={1,2,3},['secondColumn']={4,5,6}}} 
```

I see the load_table() printout followed by this error message:
invalid arguments!
stack traceback: 
        [C]: in function 'error' 
        [string "argcheck"]:152: in function 'load_table'
        df.lua:3: in main chunk
        [C]: in function 'dofile'
        ...s/tu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x0104f32d20

**Comment by gforge** [comment]
You need to wrap the table in a helper class due to the argcheck limitations:

```
require 'Dataframe'
df = Dataframe()    
df:load_table{data=Df_Dict({['firstColumn']={1,2,3},['secondColumn']={4,5,6}})} 
```

**Comment by gforge** [comment]
Thank you for reporting the issue. The README has been updated for both dev and master branches.
