### ISSUE TITLE
source code indentation

### ISSUE THREAD

**Issue by tastyminerals** [AlexMili/torch-dataframe#30]
I looked up the source code and then your contribution guidelines. Is there any particular reason for `Indentation is a tabulation of size 2`? 
I have never seen Lua code or just any other code to have tabulation size set to 2.

**Comment by AlexMili** [comment]
It's purely subjective based on our code editor settings

**Comment by gforge** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dr.max.gordon@gmail.com
    Domain gforge.se has exceeded the max emails per hour (10/10 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o10.sgmail.github.com ([167.89.101.201]:14813)
	by srv02.cpanel.pin.se with esmtps (TLSv1:DHE-RSA-AES128-SHA:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-2031-max=gforge.se@sgmail.github.com>)
	id 1cyD6M-0004E9-DJ
	for max@gforge.se; Wed, 12 Apr 2017 09:54:06 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=TB97nWxIOyZ38pb4wulawc3Mlzs=; b=wasNXcprefznY79g
	38np+6865xufCV5T5ptRJyBfS2Dcm3oBEViVAJjZj6Bk2sNwgkmOOwyAV4/0VU+w
	VrOca4aeULWDE4p5QlXDT3AUbzo9B24VquFAzxd41cZ7yl85mQDJplOlZaa3/l1J
	fNOOuL9IRLF4ZluIYv2smKX8eIY=
Received: by filter0964p1mdw1.sendgrid.net with SMTP id filter0964p1mdw1-26893-58EDDCF2-24
        2017-04-12 07:53:22.967327539 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id dB0-P0JjQwKoXgwYeu85CA
	for <max@gforge.se>; Wed, 12 Apr 2017 07:53:22.941 +0000 (UTC)
Date: Wed, 12 Apr 2017 00:53:22 -0700

**Comment by tastyminerals** [comment]
I see, it's a matter of personal taste of course, but I find this
![2017-04-12-100853_672x247_scrot](https://cloud.githubusercontent.com/assets/7676160/24947702/18c6ae16-1f68-11e7-9696-7e87c3e798e6.png)

way less pleasant to read than this?
![2017-04-12-100905_576x256_scrot](https://cloud.githubusercontent.com/assets/7676160/24947704/1bf4b57e-1f68-11e7-8764-ba7763116a11.png)

Hence my confusion.

**Comment by AlexMili** [comment]
Yes I agree, it is more pleasant to read but honestly I don't mind.

**Comment by tastyminerals** [comment]
ah, ok ) no problem, just wondered
