### ISSUE TITLE
Batch loading

### ISSUE THREAD

**Issue by gforge** [AlexMili/torch-dataframe#7]
It would be neat if the Dataframe could deliver tensor pairs for training. Since I work with images my CSV files frequently look like this:

```
| file            | gender  | weight | 
| a_pic.png       | male    |     73 | 
| another_pic.png | female  |     55 |
| ...
```

Now it would be great if to get the weight and gender as the label-tensor and the pics loaded as data tensor, i.e.:
`
data, label = my_dataframe.loadBatch(batch_no, batch_size, shuffle, data_loader_function)`

Where the `data_loader_function` expects a row and returns a tensor. The tensors are then appended at the end.

**Solution structure**

The data shuffle order should be a separate parameter set through `torch.randperm(self.n_rows)` set through `_refresh_metadata`. 

**Possible issues**

It may be tricky to do mean subtraction, we could provide a data manipulation function although that should probably be done outside the batch loader.

**Comment by AlexMili** [comment]
Great idea !
What do you mean by "tricky mean subtraction" ?

**Comment by gforge** [comment]
I mean subtracting the mean and dividing by the standard deviation for each image, see [this example](https://github.com/soumith/imagenet-multiGPU.torch/blob/master/donkey.lua#L68-L71).

I think I have a solution that works in the loadbatch-branch. I'm trying it out in my own project which is why a few additional features have crept into that branch. Have you looked at the current PR? Would be nice to proceed and delete the branches.
